# Generated by Django 4.1.1 on 2022-10-03 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_resume_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
